before_install: 
  - git fetch
  - sudo apt-get -qq update
  - sudo apt-get install wget
  - wget https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
  - unzip protoc-3.5.1-linux-x86_64.zip
  - sudo cp protoc-3.5.1-linux-x86_64/bin/protoc /usr/bin/
language: java
jdk:
  - openjdk8
cache:
  directories:
  - "$HOME/.m2"
install: mvn -s .settings.xml install --batch-mode -DskipTests=true -DprotocExecutable=/usr/bin/protoc
script: mvn -s .settings.xml install -DprotocExecutable=/usr/bin/protoc

